# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Habit WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Habit WidgetExtension

end

target 'Simple Habit Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple Habit Tracker

  target 'Simple Habit TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Simple Habit TrackerUITests' do
    # Pods for testing
  end

pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'


end
